# Generated by Django 2.1.5 on 2019-01-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_bio',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_desc',
            field=models.TextField(max_length=200),
        ),
    ]
